site_name: "GaMMA"
site_description: 'GaMMA: earthquake phase association using a bayesian gaussian mixture model'
site_author: 'Weiqiang Zhu'
docs_dir: docs/
repo_name: 'AI4EPS/GaMMA'
repo_url: 'https://github.com/ai4eps/GaMMA'
nav:
    - Overview: README.md
#    - Interactive Example: example_interactive.ipynb
#    - Synthetic Example: example_synthetic.ipynb
    - PhaseNet Example: example_phasenet.ipynb
    - Seisbench Example: example_seisbench.ipynb
theme:
  name: 'material'
plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
extra:
  analytics:
    provider: google
    property: G-Q88Y0E2EZJ
