name: pypi
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version upload to pypi'
        required: true
      pypi_repo:
        description: 'Repo to upload to (testpypi or pypi)'
        default: 'pypi'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install -U wheelhouse_uploader pyyaml
    - name: Downloading wheels and sdist from staging
      env:
        SKLEARN_VERSION: ${{ github.event.inputs.version }}
      run: |
        echo "Download $SKLEARN_VERSION wheels and sdist"
        python -m wheelhouse_uploader fetch \
          --version $SKLEARN_VERSION \
          --local-folder dist/ \
          GMMA \
          https://pypi.anaconda.org/zhuwq0/gmma/
    # - name: Check dist has the correct number of artifacts
    #   run: |
    #     python build_tools/github/check_wheels.py
    # - name: Publish package to TestPyPI
    #   uses: pypa/gh-action-pypi-publish@v1.4.1
    #   with:
    #     user: __token__
    #     password: ${{ secrets.TEST_PYPI_TOKEN }}
    #     repository_url: https://test.pypi.org/legacy/
    #   if: ${{ github.event.inputs.pypi_repo == 'testpypi' }}
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
      if: ${{ github.event.inputs.pypi_repo == 'pypi' }}
